services:
  db:
    image: mysql:8.0
    container_name: axi_db
    restart: always
    environment:
      MYSQL_DATABASE: axi_stack
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306"
    volumes:
      - db_dados:/var/lib/mysql
    networks:
      - axi_rede

  api:
    build: .
    container_name: axi_api
    restart: always
    depends_on:
      - db
    ports:
      - "3030:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/axi_stack?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123456"
    networks:
      - axi_rede

volumes:
  db_dados:

networks:
  axi_rede:
    driver: bridge